spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5432/office}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:redis}
      timeout: ${REDIS_TIMEOUT:5000}
      database: ${REDIS_DATABASE:0}

logging:
  level:
    cc.allio.uno: debug
