version: '3'
services:
  turbo:
    hostname: office-service
    container_name: office-service
    image: cc/allio/office-service:0.2
    restart: always
    ports:
      - "8700:8700"
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_TIMEOUT=${REDIS_TIMEOUT}
      - REDIS_DATABASE=${REDIS_DATABASE}
      - DATASOURCE_URL=${DATASOURCE_URL}
      - DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
      - DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - DATASOURCE_DBNAME_PRIMARY=${DATASOURCE_DBNAME_PRIMARY}
      - DATASOURCE_DBNAME_USER=${DATASOURCE_DBNAME_USER}
      - DOCUMENT_SERVER_URL=${DOCUMENT_SERVER_URL}
      - ONLYOFFICE_SERVER_URL=${ONLYOFFICE_SERVER_URL}
      - OSS_ENDPOINT=${OSS_ENDPOINT}
      - OSS_ACCESS_KEY=${OSS_ACCESS_KEY}
      - OSS_SECRET_KEY=${OSS_SECRET_KEY}
      - OSS_BUCKET=${OSS_BUCKET}
    networks:
      - allio_net

networks:
  allio_net:
    external: true
